baseURL = "https://www.bwangel.me/"
languageCode = "zh-Hans"
title = "Keep Foolish"
theme = "hugo-nuo"
enableRobotsTXT = true
pygmentsuseclasses = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "bwangel"

# Google Analytics UA number
googleAnalytics = "UA-89788711-1"


# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you likes to quote or reproduce."

[permalinks]
  post = "/:year/:month/:day/:slug/"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags"

# Add your own params here
[params]
  author = "BWANGEL"
  avatar = "/img/avatar.jpg"
  seotitle = "大白的碎碎念"
  subtitle = "闻道百，以为莫己若者，我之谓也。"
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10

  # Choose your social networks
  email = "bwangel.me@gmail.com"
  github = "bwangel23"
  # twitter = "twitter_username"
  # linkedin = "linkedin_username"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  # changyan = false
  # changyanId = "cyt3toRiB"
  # changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
